declare function bind<R>(f: () => R, thisArg: any): () => R;
declare function bind<R, A>(f: (_0: A) => R, thisArg: any): (_0: A) => R;
declare function bind<R, A>(f: (_0: A) => R, thisArg: any, _0: A): () => R;
declare function bind<R, A, B>(f: (_0: A, _1: B) => R, thisArg: any): (_0: A, _1: B) => R;
declare function bind<R, A, B>(f: (_0: A, _1: B) => R, thisArg: any, _0: A): (_1: B) => R;
declare function bind<R, A, B>(f: (_0: A, _1: B) => R, thisArg: any, _0: A, _1: B): () => R;
declare function bind<R, A, B, C>(f: (_0: A, _1: B, _2: C) => R, thisArg: any): (_0: A, _1: B, _2: C) => R;
declare function bind<R, A, B, C>(f: (_0: A, _1: B, _2: C) => R, thisArg: any, _0: A): (_1: B, _2: C) => R;
declare function bind<R, A, B, C>(f: (_0: A, _1: B, _2: C) => R, thisArg: any, _0: A, _1: B): (_2: C) => R;
declare function bind<R, A, B, C>(f: (_0: A, _1: B, _2: C) => R, thisArg: any, _0: A, _1: B, _2: C): () => R;
declare function bind<R, A, B, C, D>(f: (_0: A, _1: B, _2: C, _3: D) => R, thisArg: any): (_0: A, _1: B, _2: C, _3: D) => R;
declare function bind<R, A, B, C, D>(f: (_0: A, _1: B, _2: C, _3: D) => R, thisArg: any, _0: A): (_1: B, _2: C, _3: D) => R;
declare function bind<R, A, B, C, D>(f: (_0: A, _1: B, _2: C, _3: D) => R, thisArg: any, _0: A, _1: B): (_2: C, _3: D) => R;
declare function bind<R, A, B, C, D>(f: (_0: A, _1: B, _2: C, _3: D) => R, thisArg: any, _0: A, _1: B, _2: C): (_3: D) => R;
declare function bind<R, A, B, C, D>(f: (_0: A, _1: B, _2: C, _3: D) => R, thisArg: any, _0: A, _1: B, _2: C, _3: D): () => R;
declare function bind<R, A, B, C, D, E>(f: (_0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: any): (_0: A, _1: B, _2: C, _3: D, _4: E) => R;
declare function bind<R, A, B, C, D, E>(f: (_0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: any, _0: A): (_1: B, _2: C, _3: D, _4: E) => R;
declare function bind<R, A, B, C, D, E>(f: (_0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: any, _0: A, _1: B): (_2: C, _3: D, _4: E) => R;
declare function bind<R, A, B, C, D, E>(f: (_0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: any, _0: A, _1: B, _2: C): (_3: D, _4: E) => R;
declare function bind<R, A, B, C, D, E>(f: (_0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: any, _0: A, _1: B, _2: C, _3: D): (_4: E) => R;
declare function bind<R, A, B, C, D, E>(f: (_0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: any, _0: A, _1: B, _2: C, _3: D, _4: E): () => R;
export default bind;
