declare function bind<R, T>(f: (this: T) => R, thisArg: T): () => R;
declare function bind<R, T, A>(f: (this: T, _0: A) => R, thisArg: T): (_0: A) => R;
declare function bind<R, T, A>(f: (this: T, _0: A) => R, thisArg: T, _0: A): () => R;
declare function bind<R, T, A, B>(f: (this: T, _0: A, _1: B) => R, thisArg: T): (_0: A, _1: B) => R;
declare function bind<R, T, A, B>(f: (this: T, _0: A, _1: B) => R, thisArg: T, _0: A): (_1: B) => R;
declare function bind<R, T, A, B>(f: (this: T, _0: A, _1: B) => R, thisArg: T, _0: A, _1: B): () => R;
declare function bind<R, T, A, B, C>(f: (this: T, _0: A, _1: B, _2: C) => R, thisArg: T): (_0: A, _1: B, _2: C) => R;
declare function bind<R, T, A, B, C>(f: (this: T, _0: A, _1: B, _2: C) => R, thisArg: T, _0: A): (_1: B, _2: C) => R;
declare function bind<R, T, A, B, C>(f: (this: T, _0: A, _1: B, _2: C) => R, thisArg: T, _0: A, _1: B): (_2: C) => R;
declare function bind<R, T, A, B, C>(f: (this: T, _0: A, _1: B, _2: C) => R, thisArg: T, _0: A, _1: B, _2: C): () => R;
declare function bind<R, T, A, B, C, D>(f: (this: T, _0: A, _1: B, _2: C, _3: D) => R, thisArg: T): (_0: A, _1: B, _2: C, _3: D) => R;
declare function bind<R, T, A, B, C, D>(f: (this: T, _0: A, _1: B, _2: C, _3: D) => R, thisArg: T, _0: A): (_1: B, _2: C, _3: D) => R;
declare function bind<R, T, A, B, C, D>(f: (this: T, _0: A, _1: B, _2: C, _3: D) => R, thisArg: T, _0: A, _1: B): (_2: C, _3: D) => R;
declare function bind<R, T, A, B, C, D>(f: (this: T, _0: A, _1: B, _2: C, _3: D) => R, thisArg: T, _0: A, _1: B, _2: C): (_3: D) => R;
declare function bind<R, T, A, B, C, D>(f: (this: T, _0: A, _1: B, _2: C, _3: D) => R, thisArg: T, _0: A, _1: B, _2: C, _3: D): () => R;
declare function bind<R, T, A, B, C, D, E>(f: (this: T, _0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: T): (_0: A, _1: B, _2: C, _3: D, _4: E) => R;
declare function bind<R, T, A, B, C, D, E>(f: (this: T, _0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: T, _0: A): (_1: B, _2: C, _3: D, _4: E) => R;
declare function bind<R, T, A, B, C, D, E>(f: (this: T, _0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: T, _0: A, _1: B): (_2: C, _3: D, _4: E) => R;
declare function bind<R, T, A, B, C, D, E>(f: (this: T, _0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: T, _0: A, _1: B, _2: C): (_3: D, _4: E) => R;
declare function bind<R, T, A, B, C, D, E>(f: (this: T, _0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: T, _0: A, _1: B, _2: C, _3: D): (_4: E) => R;
declare function bind<R, T, A, B, C, D, E>(f: (this: T, _0: A, _1: B, _2: C, _3: D, _4: E) => R, thisArg: T, _0: A, _1: B, _2: C, _3: D, _4: E): () => R;
export default bind;
